@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam shadowing false

frame "cd Baz" {

interface IUsbCharger {
    
}

class StationControl {

}

class UsbChargerSimulator {
    
}

}
@enduml